.Preface

[abstract]
== Abstract

The Training Data Markup Language for Artificial Intelligence
(TrainingDML-AI) Standard aims to develop the UML model and encodings
for geospatial machine learning training data. Training data plays a
fundamental role in Earth Observation (EO) Artificial Intelligence
Machine Learning (AI/ML), especially Deep Learning (DL). It is used to
train, validate, and test AI/ML models. This Standard defines a UML
model and encodings consistent with the OGC Standards baseline to
exchange and retrieve the training data in the Web environment.

The TrainingDML-AI Standard provides detailed metadata for formalizing
the information model of training data. This includes but is not limited
to the following aspects:

* How the training data is prepared, such as provenance or quality;
* How to specify different metadata used for different ML tasks such as
scene/object/pixel levels;
* How to differentiate the high-level training data information model
and extended information models specific to various ML applications; and
* How to introduce external classification schemes and flexible means
for representing ground truth labeling.

== Security considerations

No security considerations have been made for this Standard.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
|Peng Yue |Wuhan University
|Jianya Gong |Wuhan University
|Ruixiang Liu |Wuhan University
|Dayu Yu |Wuhan University
|Samantha Lavender |Pixalytics Ltd
|Jim Antonisse |WiSC Enterprises
|Liping Di |George Mason University
|Eugene Yu |George Mason University
|Danielle Ziébelin |Laboratoire d’Informatique de Grenoble
|Boyi Shangguan |South Digital Technology Co., Ltd
|Lei Hu |South Digital Technology Co., Ltd
|Liangcun Jiang |Wuhan University of Technology
|Mingda Zhang |Hubei University
|Kai Yan |Chongqing Changan Automobile Co., Ltd
|===

== Acknowledgments

Thanks to the members of the TrainingDML-AI Standards Working Group of
the OGC as well as all contributors of change requests and comments. In
particular: Scott Simmons, Carl Reed, Ivana Ivánová, Emily Daemen, Jon
Duckworth, Zheheng Liang, Jibo Xie, Yuqi Bai, Winnie Shiu, Ignacio
Correas, Chenxiao Zhang, Zhipeng Cao, Haofeng Tan, Yinyin Pan,
Hanwen Xu, Shuaiqi Liu, Hao Li, Ming Wang, Kaixuan Wang, Haipeng Deng,
Gobe Hobona, Chris Little, Kathi Schleidt, Rodolfo Orozco.
