[conformance_class]
====
[%metadata]
identifier:: http://www.opengis.net/spec/TrainingDML-AI-1/1.0/conf/aidataquality
target:: /req/aidataquality
====

[abstract_test]
====
[%metadata]
identifier:: /conf/aidataquality/classes

target:: /req/aidataquality/classes

test-purpose:: To validate that the implementation standard correctly
implements the UML Classes defined in the Conceptual Model.

test-method-type:: Manual Inspection

test-method::
+
--
For each UML class defined or referenced in the AI_DataQuality
Package, validate as follows.
[arabic]
. Validate that the implementation standard contains a data element
which represents the same concept as that defined for the UML class.
. Validate that the data element has the same relationships with other
elements as those defined for the UML class. Validate that those
relationships have the same source, target, direction, roles, and
multiplicity as those documented in the Conceptual Model.
. Validate that the data element has the same properties (attributes)
as those specified for the UML class. Validate that those properties
have the same name, definition, type, and multiplicity of those
documented in the Conceptual Model.
. Validate that the properties of the data element include those of all
super classes of the UML class as documented in the Conceptual Model.
Validate that those properties have the same name, definition, type, and
multiplicity of those documented in the Conceptual Model.
. Validate that the associations represented for the data element
include those of all super classes of the UML class as documented in the
Conceptual Model. Validate that those representations have the same
source, target, roles, and multiplicity of those documented in the
Conceptual Model.
. Validate that the implementation standard enforces all constraints
imposed on the UML class by the Conceptual Model.
--
====