[appendix]
[[annex-ats]]
== Abstract Test Suite (Normative)

=== Introduction

Conformance is tested using the JSON Schema document which formalize the requirements described above.

=== Conformance Class: Base

The Base conformance class tests that occurrences of the basic types are encoded according to the requirements.

include::abstract_tests/ats_class_base.adoc[]

=== Conformance Class: AI_TrainingDataset

The AI_TrainingDataset conformance class tests that the training dataset object is encoded according to the requirements.

include::abstract_tests/ats_class_trainingdataset.adoc[]

=== Conformance Class: AI_TrainingData

The AI_TrainingData conformance class tests that the training data objects are encoded according to the requirements.

include::abstract_tests/ats_class_trainingdata.adoc[]

=== Conformance Class: AI_Task

The AI_Task conformance class tests that the task objects are encoded according to the requirements.

include::abstract_tests/ats_class_task.adoc[]

=== Conformance Class: AI_Label

The AI_Label conformance class tests that the label objects are encoded according to the requirements.

include::abstract_tests/ats_class_label.adoc[]

=== Conformance Class: AI_Labeling

The AI_Labeling conformance class tests that the labeling objects are encoded according to the requirements.

include::abstract_tests/ats_class_labeling.adoc[]

=== Conformance Class: AI_TDChangeset

The AI_TDChangeset conformance class tests that the TD changeset objects are encoded according to the requirements.

include::abstract_tests/ats_class_tdchangeset.adoc[]